<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class SeoStructuredData extends Model
{
    use HasFactory;

    protected $table = 'seo_structured_data';

    protected $fillable = [
        'url',
        'type',
        'schema_data',
        'is_valid',
        'errors',
        'warnings',
        'auto_generated',
    ];

    protected $casts = [
        'schema_data' => 'array',
        'errors' => 'array',
        'warnings' => 'array',
        'is_valid' => 'boolean',
        'auto_generated' => 'boolean',
    ];

    const TYPES = [
        'Product',
        'Article',
        'FAQ',
        'Breadcrumb',
        'Organization',
        'WebSite',
        'LocalBusiness',
        'Review',
        'HowTo',
        'Service',
    ];

    public function scopeValid($query)
    {
        return $query->where('is_valid', true);
    }

    public function scopeInvalid($query)
    {
        return $query->where('is_valid', false);
    }

    public function scopeByType($query, $type)
    {
        return $query->where('type', $type);
    }

    public function scopeAutoGenerated($query)
    {
        return $query->where('auto_generated', true);
    }
}
